export const APPLICATION_ACTION_TYPES = {
  GET_APPLICATION_SUCCESS: 'GET_APPLICATION_SUCCESS',
  GET_APPLICATION_FAILURE: 'GET_APPLICATION_FAILURE',
  CREATE_APP_SUCCESS: 'CREATE_APP_SUCCESS',
  CREATE_APP_FAILURE: 'CREATE_APP_FAILURE',
  DELETE_APP_SUCCESS: 'DELETE_APP_SUCCESS',
  DELETE_APP_FAILURE: 'DELETE_APP_FAILURE',
  UPDATE_APP_SUCCESS:'UPDATE_APP_SUCCESS',
  UPDATE_APP_FAILURE:'UPDATE_APP_FAILURE'
};
