export const DASHBOARD_ACTION_TYPES = {

  GET_AGENT_INFO_SUCCESS: 'GET_AGENT_INFO_SUCCESS',
  GET_AGENT_INFO_FAILURE: 'GET_AGENT_INFO_FAILURE',

  GET_LEADS_INFO_SUCCESS: 'GET_LEADS_INFO_SUCCESS',
  GET_LEADS_INFO_FAILURE: 'GET_LEADS_INFO_FAILURE',

  GET_JOIN_CALL_SUCCESS: 'GET_JOIN_CALL_SUCCESS',
  GET_JOIN_CALL_FAILURE: 'GET_JOIN_CALL_FAILURE',

  GET_CAMPAIGN_EFFICIENCY_SUCCESS: 'GET_CAMPAIGN_EFFICIENCY_SUCCESS',
  GET_CAMPAIGN_EFFICIENCY_FAILURE: 'GET_CAMPAIGN_EFFICIENCY_FAILURE',

  GET_COMMITMENTS_SUCCESS:'GET_COMMITMENTS_SUCCESS',
  GET_COMMITMENTS_FAILURE:'GET_COMMITMENTS_FAILURE',


  GET_SELF_COMMENTS_SUCCESS:'GET_SELF_COMMENTS_SUCCESS',
  GET_SELF_COMMENTS_FAILURE:'GET_SELF_COMMENTS_FAILURE',

  GET_MANAGER_COMMENTS_SUCCESS: 'GET_MANAGER_COMMENTS_SUCCESS',
  GET_MANAGER_COMMENTS_FAILURE: 'GET_MANAGER_COMMENTS_FAILURE',

  SET_SELF_COMMENTS_SUCESS:'SET_SELF_COMMENTS_SUCESS',
  SET_SELF_COMMENTS_FAILURE:'SET_SELF_COMMENTS_FAILURE',

  SET_MANAGER_COMMENTS_SUCCESS: 'SET_MANAGER_COMMENTS_SUCCESS',
  SET_MANAGER_COMMENTS_FAILURE: 'SET_MANAGER_COMMENTS_FAILURE',

  DELETE_INNER_STORE:'DELETE_INNER_STORE'

};
