export const LEAD_ACTION_TYPES = {

  GET_LEADS_SUCCESS: 'GET_LEADS_SUCCESS',
  GET_LEADS_FAILURE: 'GET_LEADS_FAILURE',

  ADD_LEADS_COMMENT_SUCCESS:'ADD_LEADS_COMMENT_SUCCESS',
  ADD_LEADS_COMMENT_FAILURE:'ADD_LEADS_COMMENT_FAILURE'
}
