export const SLL_ACTION_TYPES = {

  GET_SLL_INFO_SUCCESS: 'GET_SLL_INFO_SUCCESS',
  GET_SLL_INFO_FAILURE: 'GET_SLL_INFO_FAILURE',

  GET_SLL_EXPAND_SUCCESS: 'GET_SLL_EXPAND_SUCCESS',
  GET_SLL_EXPAND_FAILURE: 'GET_SLL_EXPAND_FAILURE',

  DELETE_SLL_EXPAND_SUCCESS:'DELETE_SLL_EXPAND_SUCCESS'

};
