export const USER_ACTION_TYPES = {

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

  GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE",

  GET_OUTLETS_SUCCESS:"GET_OUTLETS_SUCCESS",
  GET_OUTLETS_FAILURE:"GET_OUTLETS_FAILURE",

  SET_VENDOR_NEW_SUCCESS:"SET_VENDOR_NEW_SUCCESS",
  SET_VENDOR_NEW_FAILURE:"SET_VENDOR_NEW_FAILURE",

  SET_VENDOR_FULL_SUCCESS:"SET_VENDOR_FULL_SUCCESS",
  SET_VENDOR_FULL_FAILURE:"SET_VENDOR_FULL_FAILURE",

  LOGOUT: 'LOGOUT'

}
